#include "Generation/Includes/Noise.hlsl"
#include "Generation/Includes/Point.hlsl"
// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

static const int numThreads = 8;

RWStructuredBuffer<Point> points;
int numPointsPerAxis;

float3 sphereCenter;
float radius;
float radiusSq;

bool breaking;

RWStructuredBuffer<int> ammos;

[numthreads(numThreads, numThreads, numThreads)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // Stop if out of range
    if (id.x >= numPointsPerAxis || id.y >= numPointsPerAxis || id.z >= numPointsPerAxis)
    {
        return;
    }
    
    uint index = id.x + id.y * numPointsPerAxis+ id.z * numPointsPerAxis * numPointsPerAxis;

    Point p = points[index];
    float3 pos = p.position;

    float3 diff = pos - sphereCenter;
    float distSq = dot(diff, diff);

    if (distSq <= radiusSq)
    {
        float dist = sqrt(distSq);
        float t = 1.0 - (distSq / radiusSq);
        float densityChange = breaking ? -t : t;
        
        // When breaking add to the ammo
        if (breaking)
            ammos[p.material]++;
        
        p.density = max(p.density + densityChange, 0.0);
        points[index] = p;
    }
}
