// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel March
#include "Includes/MarchTables.hlsl"
#include "Includes/Point.hlsl"

static const int numThreads = 8;

struct Triangle
{
    float3 vertexC;
    float3 vertexB;
    float3 vertexA;
};

AppendStructuredBuffer<Triangle> triangles;
StructuredBuffer<Point> points;

int numPointsPerAxis;
float surfaceLevel;

float3 interpolateVerts(Point v1, Point v2)
{
    float t = (surfaceLevel - v1.density) / (v2.density - v1.density);
    return v1.position + t * (v2.position - v1.position);
}

int indexFromCoord(int x, int y, int z)
{
    return z * numPointsPerAxis * numPointsPerAxis + y * numPointsPerAxis + x;
}

[numthreads(numThreads, numThreads, numThreads)] // Meaning sizes can only be times 10
void March(uint3 id : SV_DispatchThreadID)
{
    // Stop one point before the end because voxel includes neighbouring points
    if (id.x >= numPointsPerAxis - 1 || id.y >= numPointsPerAxis - 1 || id.z >= numPointsPerAxis - 1)
    {
        return;
    }
    
    // 8 corners of the current cube
    Point cubeCorners[8] =
    {
        points[indexFromCoord(id.x, id.y, id.z)],
        points[indexFromCoord(id.x + 1, id.y, id.z)],
        points[indexFromCoord(id.x + 1, id.y, id.z + 1)],
        points[indexFromCoord(id.x, id.y, id.z + 1)],
        points[indexFromCoord(id.x, id.y + 1, id.z)],
        points[indexFromCoord(id.x + 1, id.y + 1, id.z)],
        points[indexFromCoord(id.x + 1, id.y + 1, id.z + 1)],
        points[indexFromCoord(id.x, id.y + 1, id.z + 1)]
    };
    
    // Calculate unique index for each cube configuration.
    // There are 256 possible values
    // A value of 0 means cube is entirely inside surface; 255 entirely outside.
    // The value is used to look up the edge table, which indicates which edges of the cube are cut by the isosurface.    
    
    int cubeIndex = 0;
    if (cubeCorners[0].density < surfaceLevel)
        cubeIndex |= 1;
    if (cubeCorners[1].density < surfaceLevel)
        cubeIndex |= 2;
    if (cubeCorners[2].density < surfaceLevel)
        cubeIndex |= 4;
    if (cubeCorners[3].density < surfaceLevel)
        cubeIndex |= 8;
    if (cubeCorners[4].density < surfaceLevel)
        cubeIndex |= 16;
    if (cubeCorners[5].density < surfaceLevel)
        cubeIndex |= 32;
    if (cubeCorners[6].density < surfaceLevel)
        cubeIndex |= 64;
    if (cubeCorners[7].density < surfaceLevel)
        cubeIndex |= 128;
    
    
    for (int i = 0; TriValue(cubeIndex, i) != -1; i += 3)
    {
        // Get indices of corner points A and B for each of the three edges
        // of the cube that need to be joined to form the triangle.
        int a0 = cornerIndexAFromEdge[TriValue(cubeIndex, i)];
        int b0 = cornerIndexBFromEdge[TriValue(cubeIndex, i)];
        
        int a1 = cornerIndexAFromEdge[TriValue(cubeIndex, i + 1)];
        int b1 = cornerIndexBFromEdge[TriValue(cubeIndex, i + 1)];
        
        int a2 = cornerIndexAFromEdge[TriValue(cubeIndex, i + 2)];
        int b2 = cornerIndexBFromEdge[TriValue(cubeIndex, i + 2)];

        Triangle tri;
        tri.vertexA = interpolateVerts(cubeCorners[a0], cubeCorners[b0]);
        tri.vertexB = interpolateVerts(cubeCorners[a1], cubeCorners[b1]);
        tri.vertexC = interpolateVerts(cubeCorners[a2], cubeCorners[b2]);
        triangles.Append(tri);
    }
}
