#pragma kernel Density
#include "Includes/Density.hlsl"
#include "Includes/Noise.hlsl"

[numthreads(numThreads, numThreads, numThreads)]
void Density(int3 id : SV_DispatchThreadID)
{
    // Bounds check
    if (id.x >= numPointsPerAxis ||
        id.y >= numPointsPerAxis ||
        id.z >= numPointsPerAxis)
    {
        return;
    }

    // World-space position of this point
    float3 pos = chunkCentre + id * spacing - boundsSize / 2;

    int index = indexFromCoord(id.x, id.y, id.z);
    
    float n = snoise((pos) * 0.5);
    
    int mat = 0;
    
    if (n > 0.5f)
        mat = 1;
    
    points[index].material = mat;
    points[index].position = pos;
    points[index].density = 1.0f;
}